/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author neyder 
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Modelo.Vehiculo;
import Modelo.Persona;

public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    List<Vehiculo> vehiculoList=null;
    List<Persona> personaList=null;
    
    int contador=0;
    
    public Registro() {
        
        initComponents();
        
        personaList=new ArrayList<>();
        vehiculoList=new ArrayList<>();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehiculoPanel = new javax.swing.JPanel();
        Lplaca = new javax.swing.JLabel();
        Lmodelo = new javax.swing.JLabel();
        Lmarca = new javax.swing.JLabel();
        Ldueño = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        dueñoTxt = new javax.swing.JTextField();
        consultarB = new javax.swing.JButton();
        guardarB = new javax.swing.JButton();
        propietarioPanel = new javax.swing.JPanel();
        Lnombre = new javax.swing.JLabel();
        Lapellido = new javax.swing.JLabel();
        Lcedula = new javax.swing.JLabel();
        Lcontacto = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        cedulaTxt = new javax.swing.JTextField();
        contactoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vehiculoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vehiculo"));

        Lplaca.setText("Placa:");

        Lmodelo.setText("Modelo:");

        Lmarca.setText("Marca:");

        Ldueño.setText("Dueño:");

        consultarB.setText("Consultar");
        consultarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBActionPerformed(evt);
            }
        });

        guardarB.setText("Guardar");
        guardarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehiculoPanelLayout = new javax.swing.GroupLayout(vehiculoPanel);
        vehiculoPanel.setLayout(vehiculoPanelLayout);
        vehiculoPanelLayout.setHorizontalGroup(
            vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculoPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiculoPanelLayout.createSequentialGroup()
                        .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(vehiculoPanelLayout.createSequentialGroup()
                                .addComponent(Ldueño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dueñoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vehiculoPanelLayout.createSequentialGroup()
                                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lmodelo)
                                    .addComponent(Lplaca)
                                    .addComponent(Lmarca))
                                .addGap(25, 25, 25)
                                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(marcaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(modeloTxt)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(vehiculoPanelLayout.createSequentialGroup()
                        .addComponent(consultarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarB)))
                .addContainerGap())
        );
        vehiculoPanelLayout.setVerticalGroup(
            vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lplaca)
                    .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lmodelo)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lmarca)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ldueño)
                    .addComponent(dueñoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarB)
                    .addComponent(guardarB))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        propietarioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Propietario"));

        Lnombre.setText("Nombre:");

        Lapellido.setText("Apellido:");

        Lcedula.setText("Cedula:");

        Lcontacto.setText("Contacto:");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propietarioPanelLayout = new javax.swing.GroupLayout(propietarioPanel);
        propietarioPanel.setLayout(propietarioPanelLayout);
        propietarioPanelLayout.setHorizontalGroup(
            propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propietarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propietarioPanelLayout.createSequentialGroup()
                        .addGroup(propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(propietarioPanelLayout.createSequentialGroup()
                                .addComponent(Lcontacto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contactoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addGroup(propietarioPanelLayout.createSequentialGroup()
                                .addComponent(Lcedula)
                                .addGap(18, 18, 18)
                                .addComponent(cedulaTxt))
                            .addGroup(propietarioPanelLayout.createSequentialGroup()
                                .addComponent(Lapellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(propietarioPanelLayout.createSequentialGroup()
                        .addComponent(Lnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        propietarioPanelLayout.setVerticalGroup(
            propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propietarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lapellido))
                .addGap(9, 9, 9)
                .addGroup(propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcedula)
                    .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(propietarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcontacto)
                    .addComponent(contactoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        areaTxt.setColumns(20);
        areaTxt.setRows(5);
        jScrollPane1.setViewportView(areaTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(vehiculoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propietarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propietarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehiculoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(){
    placaTxt.setText("");
    modeloTxt.setText("");
    marcaTxt.setText("");
    dueñoTxt.setText("");
    cedulaTxt.setText("");
    nameTxt.setText("");
    apellidoTxt.setText("");
    contactoTxt.setText("");
    }
    
    
    
    
    private void guardarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBActionPerformed
       
        Vehiculo v = new Vehiculo();
        
        v.setPlaca(placaTxt.getText());
        v.setModelo(Integer.parseInt(modeloTxt.getText()));
        v.setMarca(marcaTxt.getText());
        v.setDueño(dueñoTxt.getText()); 
        
        vehiculoList.add(v);
               
        Persona p = new Persona();
        
        p.setCedula(cedulaTxt.getText());
        p.setNombre(nameTxt.getText());
        p.setApellido(apellidoTxt.getText());
        p.setContacto(contactoTxt.getText());
        
        personaList.add(p);
        
        for(int i=0;i<=personaList.size();i++){
         
            if(personaList.get(i).equals(dueñoTxt.getText())){
            contador=contador+1;
            }
        } 
         
    
        JOptionPane.showMessageDialog(null,"Vehiculo y propietario almacenado");
        limpiar();
    }//GEN-LAST:event_guardarBActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void consultarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBActionPerformed
        
         Boolean aux=false;
                  
         
            if(dueñoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"campo de dueño vacio!!");
            }
            else
            {       
              for(int i=0;i<=vehiculoList.size();i++){
                           
                if(personaList.get(i).equals(dueñoTxt.getText())){
                    aux=true;                                     
                 }
                  if(aux=true){ 
                     areaTxt.setText(vehiculoList.get(i).toString()+personaList.get(i).toString()+"\nEsta persona tiene "+contador+" vehiculos.");
                     //areaTxt.setText("Usuario registrado.");                     
                 }
                    else{
                         areaTxt.setText("\nEl Usuario no esta registrado.");
                    }
                }
            }
        
    }//GEN-LAST:event_consultarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Lapellido;
    public javax.swing.JLabel Lcedula;
    public javax.swing.JLabel Lcontacto;
    public javax.swing.JLabel Ldueño;
    public javax.swing.JLabel Lmarca;
    public javax.swing.JLabel Lmodelo;
    public javax.swing.JLabel Lnombre;
    public javax.swing.JLabel Lplaca;
    public javax.swing.JTextField apellidoTxt;
    public javax.swing.JTextArea areaTxt;
    public javax.swing.JTextField cedulaTxt;
    public javax.swing.JButton consultarB;
    public javax.swing.JTextField contactoTxt;
    public javax.swing.JTextField dueñoTxt;
    private javax.swing.JButton guardarB;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField marcaTxt;
    public javax.swing.JTextField modeloTxt;
    public javax.swing.JTextField nameTxt;
    public javax.swing.JTextField placaTxt;
    public javax.swing.JPanel propietarioPanel;
    public javax.swing.JPanel vehiculoPanel;
    // End of variables declaration//GEN-END:variables
}
